version: '3'

services:
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'myjenkins'
        restart: always
        ports:
            - '8200:8080'
            - '50200:50000'
        expose:
            - '8080'
            - '50000'
        volumes:
            - './jenkins_home:/var/jenkins_home'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './docker-compose-Linux-x86_64:/usr/local/bin/docker-compose'
        environment:
            TZ: "Asia/Seoul"
networks:
    default:
        external:
            name: devops
