version: '3'

services:
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: myjenkins
        restart: always
        ports:
            - $JENKINS_PORT:8080
            - 50200:50000
        expose:
            - 8080
            - 50000
        volumes:
            - ./jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - ./docker-compose-Linux-x86_64:/usr/local/bin/docker-compose
            - nginx_log:$LOG_NGINX
            - tomcat_log1:$LOG_TOMCAT_1
            - tomcat_log2:$LOG_TOMCAT_2
        environment:
            TZ: Asia/Seoul
networks:
    default:
        external:
            name: devops
volumes: 
    nginx_log:
        external: true
    tomcat_log1:
        external: true
    tomcat_log2:
        external: true

